#Extensive Definition Language - XDL
#PROJECT-VOX branch compiler

all:
	@echo $(shell date): Compiling Extensive Direct Language [XDL] library at $(shell hostname)
	@g++ -o xdl_program_test xdl_struct.cpp
	@echo Extensive Direct Language library [XDL] lib compiled!
run:
	@echo $(shell date): Runing Extensive Direct Language [XDL] library at $(shell hostname)
	@./xdl_program_test
	@echo Test completed!

clean:
	@echo $(shell date): Cleaning Extensive Direct Language library compiled...
	@rm xdl_program_test
	@echo $(shell date): Cleaned